site_name: po18
site_author: po18官网
site_description: po18·(脸红心跳文小说)官方网站-入口
theme:
  name: readthedocs
nav:
  - Home: index.md
  - About: about.md
  - Features: features.md
  - Contact: contact.md
theme:
  name: material
nav:
  - Home: index.md
  - Content: content.md
